/*
 * Copyright (C) 2015 leo
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package application.swing_utils;

import application.model.TagTableModel;
import cache.Cache;

/**
 *
 * @author leo
 */
public class MemoryViewer extends javax.swing.JPanel {

    /**
     * Creates new form MemoryViewer
     */
    public MemoryViewer() {
        initComponents();
    }
    
    public void setCache(Cache c) {
        System.out.println("instance of c : " + c.getClass().toString());
        cacheVisualisator.setCache(c);
        scrollViewer1.linkTo(cacheVisualisator);
        update();
    }
    
    public Cache getCache() {
        return cacheVisualisator.getCache();
    }
    
    public void update() {
        scrollViewer1.update();
    }
    
    public void changeMethod(TagTableModel.Method m) {
        cacheVisualisator.changeMethod(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        affichageGroupButton = new javax.swing.ButtonGroup();
        cacheVisualisator = new application.swing_utils.CacheVisualisator();
        scrollViewer1 = new application.swing_utils.ScrollViewer();

        setLayout(new java.awt.BorderLayout());
        add(cacheVisualisator, java.awt.BorderLayout.CENTER);
        add(scrollViewer1, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup affichageGroupButton;
    private application.swing_utils.CacheVisualisator cacheVisualisator;
    private application.swing_utils.ScrollViewer scrollViewer1;
    // End of variables declaration//GEN-END:variables
}
