/*
 * Copyright (C) 2015 leo
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package application.swing_utils;

import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JScrollBar;

/**
 *
 * @author leo
 */
public class ScrollViewer extends javax.swing.JPanel {
    /**
     * Creates new form ScrollViewer
     */
    public ScrollViewer() {
        initComponents();
        
        addMouseMotionListener(new MouseMotionAdapter() {

            @Override
            public void mouseDragged(MouseEvent e) {
                final int y = e.getYOnScreen();
                final int h = getHeight();
                JScrollBar v = jScrollPane1.getVerticalScrollBar();

                if (y > (h / 4) * 3) {
                    v.setValue(v.getValue() + 5);

                } else if (y < (h / 4))  {
                    v.setValue(v.getValue() - 5);
                }

                scrollViewer_core1.setRegion(e.getY());
            }
            
        });
    }
    
    public void update() {
        scrollViewer_core1.update();
    }
    
    public void linkTo(CacheVisualisator cV) {
        scrollViewer_core1.linkTo(cV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        scrollViewer_core1 = new application.swing_utils.ScrollViewer_core();

        setMaximumSize(new java.awt.Dimension(16, 2147483647));
        setMinimumSize(new java.awt.Dimension(16, 22));
        setPreferredSize(new java.awt.Dimension(16, 300));
        setVerifyInputWhenFocusTarget(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(16, 7));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(16, 100));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        scrollViewer_core1.setMinimumSize(new java.awt.Dimension(16, 0));

        javax.swing.GroupLayout scrollViewer_core1Layout = new javax.swing.GroupLayout(scrollViewer_core1);
        scrollViewer_core1.setLayout(scrollViewer_core1Layout);
        scrollViewer_core1Layout.setHorizontalGroup(
            scrollViewer_core1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        scrollViewer_core1Layout.setVerticalGroup(
            scrollViewer_core1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.add(scrollViewer_core1);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scrollViewer_core1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollViewer_core1MouseDragged
        
        final int y = evt.getYOnScreen();
        final int h = getHeight();
        JScrollBar v = jScrollPane1.getVerticalScrollBar();

        if (y > (h / 4) * 3) {
            v.setValue(v.getValue() + 5);

        } else if (y < (h / 4))  {
            v.setValue(v.getValue() - 5);
        }

        scrollViewer_core1.setRegion(evt.getY());
    }//GEN-LAST:event_scrollViewer_core1MouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private application.swing_utils.ScrollViewer_core scrollViewer_core1;
    // End of variables declaration//GEN-END:variables
}
